import 'localization_keys.dart';

final Map<String, String> hi = {
  appName: 'भाषावर्स',
  selectAppLanguage: 'ऐप्लिकेशन की भाषा चुनें',
  youCanAlwaysChange: 'आप सेटिंग से इसे कभी भी बदल सकते हैं।',
  searchLanguage: 'सर्च भाषा',
  continueText: 'जारी रखें',
  next: 'आगे',
  skip: 'स्किप',
  getStarted: 'आरंभ करें',
  speechRecognition: 'वाक् पहचान',
  automaticallyRecognizeAndConvert:
      'स्वचालित रूप से पहचानें और अपनी आवाज को टेक्स्ट में बदलें',
  speechToSpeechTranslation: 'स्पीच टू स्पीच ट्रांसलेशन',
  translateYourVoiceInOneIndianLanguage:
      'अपनी आवाज़ का एक भारतीय भाषा से दूसरी भारतीय भाषा में अनुवाद करें',
  languageTranslation: 'भाषा का अनुवाद',
  translateSentencesFromOneIndianLanguageToAnother:
      'वाक्यों का एक भारतीय भाषा से दूसरी भाषा में अनुवाद करें',
  bhashaverseChatBot: 'भाषावर्स चैट बॉट',
  selectVoiceAssistant: 'ध्वनि सहायक अवतार चुनें',
  youWillHearTheTranslationText:
      'आपके द्वारा चुने गए अवतार की आवाज में आपको अनुवाद सुनाई देगा। आप सेटिंग से कभी भी अवतार बदल सकते हैं।',
  male: 'पुरुष',
  female: 'स्त्री',
  letsTranslate: 'अनुवाद शूरू करें',
  appTheme: 'ऐप थीम',
  appInterfaceWillChange: 'एप्लिकेशन इंटरफ़ेस तदनुसार चयनित मोड में बदल जाएगा',
  light: 'लाइट',
  dark: 'डार्क',
  systemDefault: 'सिस्टम डिफ़ॉल्ट',
  appLanguage: 'ऐप भाषा',
  appInterfaceWillChangeInSelected: 'ऐप इंटरफ़ेस चयनित ऐप भाषा में बदल जाएगा।',
  voiceAssistant: 'ध्वनि सहायक',
  transLiteration: 'लिप्यंतरण',
  transLiterationWillInitiateWord:
      'लिप्यंतरण आपके टाइप करते समय शब्द सुझाव आरंभ करेगा',
  advanceSettings: 'एडवांस सेटिंग',
  kTranslation: 'अनुवाद',
  kChat: 'बात करना',
  kSettings: 'सेटिंग्स',
  kHomeLoadingAnimationText: 'हम आपके लिए चीज़ें सेट कर रहे हैं...',
  kTranslateSourceTitle: 'से अनुवाद करें',
  kTranslateTargetTitle: 'अनुवाद करें',
  kTranslationHintText: 'लिखना शुरू करें या माइक को दबाएं',
  kListeningHintText: 'सुन रहे हैं , आप बोलना जारी रखें...',
  kPaste: 'पेस्ट',
  kTranslate: 'अनुवाद',
  kReset: 'रीसेट',
  kErrorNoSourceText: 'कृपया पहले वाक्य दर्ज करें',
  kErrorSelectSourceAndTargetScreen: 'कृपया पहले भाषा चुनें',
  errorMicPermission: 'साउंड रिकॉर्ड करने के लिए माइक अनुमति चाहिए',
  errorInRecording: 'वॉयस रिकॉर्डिंग में त्रुटि',
  noVoiceAssistantAvailable: 'इस समय कोई ध्वनि सहायक उपलब्ध नहीं है',
  kTranslationLoadingAnimationText:
      'अनुवाद कर रहे हैं, कृपया प्रतीक्षा करें...',
  errorPleaseSelectLanguage: 'कृपया भाषा चुनें',
  featureAvailableSoonInfo: 'यह सुविधा जल्द ही उपलब्ध होगी',
  errorSelectVoiceAssistant: 'कृपया ध्वनि सहायक अवतार चुनें',
  noTextForShare: 'साझा करने के लिए कोई टेक्स्ट नहीं मिला',
  noTextForCopy: 'कॉपी के लिए कोई टेक्स्ट नहीं मिला',
  textCopiedToClipboard: 'क्लिपबोर्ड पर टेक्स्ट कॉपी किया गया',
  femaleVoiceAssistantNotAvailable:
      'स्त्री वॉयस असिस्टेंट उपलब्ध नहीं है, पुरुष वॉयस असिस्टेंट से ध्वनि चल रही है',
  maleVoiceAssistantNotAvailable:
      'पुरुष वॉइस असिस्टेंट उपलब्ध नहीं है, स्त्री वॉइस असिस्टेंट से ध्वनि चल रही है',
  errorNoTextInClipboard: 'क्लिपबोर्ड में कोई टेक्स्ट उपलब्ध नहीं है',
  s2sStreaming: 'S2S स्ट्रीमिंग',
  connecting: 'कनेक्ट हो रहा है...',
  somethingWentWrong: 'कुछ गलत हुआ',
  tapAndHoldForRecording: 'रिकॉर्डिंग के लिए कृपया माइक को टैप करके रखें',
};
