List<String> langCodeList = [
  'en',
  'hi',
  'mr',
  'bn',
  'pa',
  'gu',
  'or',
  'ta',
  'te',
  'kn',
  'ur',
  'doi',
  'ne',
  'si',
  'sa',
  'as',
  'mai',
  'bho',
  'ml',
  'raj',
  'brx',
  'mni',
  'ks',
  'kok',
  'sd',
  'sat',
];

class LanguageMapTranslated {
  static Map<String, Map<String, String>> langMap = {
    // English
    langCodeList[0]: {
      langCodeList[0]: 'English',
      langCodeList[1]: 'Hindi',
      langCodeList[2]: 'Marathi',
      langCodeList[3]: 'Bangla',
      langCodeList[4]: 'Punjabi',
      langCodeList[5]: 'Gujarati',
      langCodeList[6]: 'Odia',
      langCodeList[7]: 'Tamil',
      langCodeList[8]: 'Telugu',
      langCodeList[9]: 'Kannada',
      langCodeList[10]: 'Urdu',
      langCodeList[11]: 'Dogri',
      langCodeList[12]: 'Nepali',
      langCodeList[13]: 'Sinhala',
      langCodeList[14]: 'Sanskrit',
      langCodeList[15]: 'Assamese',
      langCodeList[16]: 'Maithili',
      langCodeList[17]: 'Bhojpuri',
      langCodeList[18]: 'Malayalam',
      langCodeList[19]: 'Rajasthani',
      langCodeList[20]: 'Bodo',
      langCodeList[21]: 'Manipuri',
      langCodeList[22]: 'Kashmiri',
      langCodeList[23]: 'Konkani',
      langCodeList[24]: 'Sindhi',
      langCodeList[25]: 'Santali',
    },
    // Hindi
    langCodeList[1]: {
      langCodeList[0]: 'अंग्रेजी',
      langCodeList[1]: 'हिंदी',
      langCodeList[2]: 'मराठी',
      langCodeList[3]: 'बांग्ला',
      langCodeList[4]: 'पंजाबी',
      langCodeList[5]: 'गुजराती',
      langCodeList[6]: 'ओड़िया',
      langCodeList[7]: 'तमिल',
      langCodeList[8]: 'तेलुगु',
      langCodeList[9]: 'कन्नड़',
      langCodeList[10]: 'उर्दू',
      langCodeList[11]: 'डोगरी',
      langCodeList[12]: 'नेपाली',
      langCodeList[13]: 'सिंहली',
      langCodeList[14]: 'संस्कृत',
      langCodeList[15]: 'असमिया',
      langCodeList[16]: 'मैथिली',
      langCodeList[17]: 'भोजपुरी',
      langCodeList[18]: 'मलयालम',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'मणिपुरी',
      langCodeList[22]: 'कश्मीरी',
      langCodeList[23]: 'कोंकणी',
      langCodeList[24]: 'सिंधी',
      langCodeList[25]: 'संथाली'
    },
    // Marathi
    langCodeList[2]: {
      langCodeList[0]: 'इंग्रजी ',
      langCodeList[1]: 'हिंदी ',
      langCodeList[2]: 'मराठी ',
      langCodeList[3]: 'बंगाली ',
      langCodeList[4]: 'पंजाबी ',
      langCodeList[5]: 'गुजराती ',
      langCodeList[6]: 'उडिया ',
      langCodeList[7]: 'तमिळ ',
      langCodeList[8]: 'तेलुगू ',
      langCodeList[9]: 'कानडी ',
      langCodeList[10]: 'उर्दू ',
      langCodeList[11]: 'डोगरी ',
      langCodeList[12]: 'नेपाळी ',
      langCodeList[13]: 'सिंहली ',
      langCodeList[14]: 'संस्कृत ',
      langCodeList[15]: 'आसामी ',
      langCodeList[16]: 'मैथिली ',
      langCodeList[17]: 'भोजपुरी ',
      langCodeList[18]: 'मल्याळम',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'मणिपुरी ',
      langCodeList[22]: 'काश्मिरी ',
      langCodeList[23]: 'कोंकणी ',
      langCodeList[24]: 'सिंधी ',
      langCodeList[25]: ''
    },
    // Bangla
    langCodeList[3]: {
      langCodeList[0]: 'ইংরেজি',
      langCodeList[1]: 'হিন্দি',
      langCodeList[2]: 'মারাঠি',
      langCodeList[3]: 'বাংলা',
      langCodeList[4]: 'পাঞ্জাবি',
      langCodeList[5]: 'গুজরাটি',
      langCodeList[6]: 'ওড়িয়া',
      langCodeList[7]: 'তামিল',
      langCodeList[8]: 'তেলুগু',
      langCodeList[9]: 'কন্নড়',
      langCodeList[10]: 'উর্দূ',
      langCodeList[11]: 'ডোগরি',
      langCodeList[12]: 'নেপালি',
      langCodeList[13]: 'সিংহলি',
      langCodeList[14]: 'সংস্কৃত',
      langCodeList[15]: 'অসমীয়া',
      langCodeList[16]: 'মৈথিলি',
      langCodeList[17]: 'ভোজপুরি',
      langCodeList[18]: 'মালয়ালম',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'মণিপুরি',
      langCodeList[22]: 'কাশ্মীরি',
      langCodeList[23]: 'কোঙ্কনি',
      langCodeList[24]: 'সিন্ধি',
      langCodeList[25]: 'সাঁওতালি'
    },
    // Odia
    langCodeList[6]: {
      langCodeList[0]: 'ଇଂରାଜୀ',
      langCodeList[1]: 'ହିନ୍ଦୀ',
      langCodeList[2]: 'ମରାଠୀ',
      langCodeList[3]: 'ବାଂଲା',
      langCodeList[4]: 'ପଞ୍ଜାବୀ',
      langCodeList[5]: 'ଗୁଜରାଟୀ',
      langCodeList[6]: 'ଓଡ଼ିଆ',
      langCodeList[7]: 'ତାମିଲ',
      langCodeList[8]: 'ତେଲୁଗୁ',
      langCodeList[9]: 'କନ୍ନଡ଼',
      langCodeList[10]: 'ଉର୍ଦ୍ଦୁ',
      langCodeList[11]: 'ଡୋଗରୀ',
      langCodeList[12]: 'ନେପାଳୀ',
      langCodeList[13]: 'ସିଂହଳୀ',
      langCodeList[14]: 'ସଂସ୍କୃତ',
      langCodeList[15]: 'ଅସମିୟା',
      langCodeList[16]: 'ମୈଥିଳି',
      langCodeList[17]: 'ଭୋଜପୁରୀ',
      langCodeList[18]: 'ମାଲୟାଲମ',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'ମଣିପୁରୀ',
      langCodeList[22]: 'କାଶ୍ମିରୀ',
      langCodeList[23]: 'କୋଙ୍କଣୀ',
      langCodeList[24]: 'ସିନ୍ଧି',
      langCodeList[25]: 'ସାନ୍ତାଳୀ'
    },
    // Tamil
    langCodeList[7]: {
      langCodeList[0]: 'ஆங்கிலம்',
      langCodeList[1]: 'ஹிந்தி',
      langCodeList[2]: 'மராத்தி',
      langCodeList[3]: 'பெங்காலி',
      langCodeList[4]: 'பஞ்சாபி',
      langCodeList[5]: 'குஜராத்தி',
      langCodeList[6]: 'ஒரியா',
      langCodeList[7]: 'தமிழ்',
      langCodeList[8]: 'தெலுங்கு',
      langCodeList[9]: 'கன்னடம்',
      langCodeList[10]: 'உருது',
      langCodeList[11]: 'டோக்ரி',
      langCodeList[12]: 'நேபாளி',
      langCodeList[13]: 'சிங்களம்',
      langCodeList[14]: 'சமஸ்கிருதம்',
      langCodeList[15]: 'அசாமி',
      langCodeList[16]: 'மைதிலி',
      langCodeList[17]: 'போஜ்புரி',
      langCodeList[18]: 'மலையாளம்',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'மணிப்பூரி',
      langCodeList[22]: 'காஷ்மீரி',
      langCodeList[23]: 'கொங்கனி',
      langCodeList[24]: 'சிந்தி',
      langCodeList[25]: 'சந்தாலி'
    },
    // Telugu
    langCodeList[8]: {
      langCodeList[0]: 'ఆంగ్లము',
      langCodeList[1]: 'హిందీ',
      langCodeList[2]: 'మరాఠి',
      langCodeList[3]: 'బంగ్లా',
      langCodeList[4]: 'పంజాబీ',
      langCodeList[5]: 'గుజరాతీ',
      langCodeList[6]: 'ఒడియా',
      langCodeList[7]: 'తమిళ్',
      langCodeList[8]: 'తెలుగు',
      langCodeList[9]: 'కన్నడ',
      langCodeList[10]: 'ఉర్దూ',
      langCodeList[11]: 'డోగ్రీ',
      langCodeList[12]: 'నేపాలీ',
      langCodeList[13]: 'సింహళ',
      langCodeList[14]: 'సంస్కృతం',
      langCodeList[15]: 'ఆసామీస్',
      langCodeList[16]: 'మైథిలి',
      langCodeList[17]: 'భోజ్‌పురీ',
      langCodeList[18]: 'మలయాళం',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'మణిపురీ',
      langCodeList[22]: 'కాశ్మీరీ',
      langCodeList[23]: 'కొంకణీ',
      langCodeList[24]: 'సింధీ',
      langCodeList[25]: 'సంతాలీ'
    },
    // Kannada
    langCodeList[9]: {
      langCodeList[0]: 'ಆಂಗ್ಲ',
      langCodeList[1]: 'ಹಿಂದಿ',
      langCodeList[2]: 'ಮರಾಠಿ',
      langCodeList[3]: 'ಬಾಂಗ್ಲಾ',
      langCodeList[4]: 'ಪಂಜಾಬಿ',
      langCodeList[5]: 'ಗುಜರಾತಿ',
      langCodeList[6]: 'ಒಡಿಯಾ',
      langCodeList[7]: 'ತಮಿಳು',
      langCodeList[8]: 'ತೆಲುಗು',
      langCodeList[9]: 'ಕನ್ನಡ',
      langCodeList[10]: 'ಉರ್ದು',
      langCodeList[11]: 'ಡೋಗ್ರಿ',
      langCodeList[12]: 'ನೇಪಾಳಿ',
      langCodeList[13]: 'ಸಿಂಹಳ',
      langCodeList[14]: 'ಸಂಸ್ಕೃತ',
      langCodeList[15]: 'ಅಸ್ಸಾಮಿ',
      langCodeList[16]: 'ಮೈಥಿಲಿ',
      langCodeList[17]: 'ಭೋಜಪುರಿ',
      langCodeList[18]: 'ಮಲಯಾಳಂ',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'ಮಣಿಪುರಿ',
      langCodeList[22]: 'ಕಾಶ್ಮೀರಿ',
      langCodeList[23]: 'ಕೊಂಕಣಿ',
      langCodeList[24]: 'ಸಿಂಧಿ',
      langCodeList[25]: 'ಸಂತಾಲಿ'
    },
    // Sanskrit
    langCodeList[14]: {
      langCodeList[0]: 'आङ्ग्ला',
      langCodeList[1]: 'हिन्दी',
      langCodeList[2]: 'मराठी',
      langCodeList[3]: 'बाङ्ग्ला',
      langCodeList[4]: 'पञ्जाबी',
      langCodeList[5]: 'गुजराती',
      langCodeList[6]: 'ओडिया',
      langCodeList[7]: 'तमिळु',
      langCodeList[8]: 'तेलुगु',
      langCodeList[9]: 'कन्नडा',
      langCodeList[10]: 'उर्दू',
      langCodeList[11]: 'डोग्री',
      langCodeList[12]: 'नेपाली',
      langCodeList[13]: 'सिंहला',
      langCodeList[14]: 'संस्कृतम्',
      langCodeList[15]: 'अस्सामी',
      langCodeList[16]: 'मैथिली',
      langCodeList[17]: 'भोजपुरी',
      langCodeList[18]: 'मलयाळम्',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'मणिपुरी',
      langCodeList[22]: 'काश्मीरी',
      langCodeList[23]: 'कङ्कणी',
      langCodeList[24]: 'सिन्धी',
      langCodeList[25]: 'सन्तली'
    },
    // Assamese
    langCodeList[15]: {
      langCodeList[0]: 'ইংৰাজী',
      langCodeList[1]: 'হিন্দী',
      langCodeList[2]: 'মাৰাঠী',
      langCodeList[3]: 'বাংলা',
      langCodeList[4]: 'পাঞ্জাবী',
      langCodeList[5]: 'গুজৰাটী',
      langCodeList[6]: 'ওড়িয়া',
      langCodeList[7]: 'তামিল',
      langCodeList[8]: 'তেলেগু',
      langCodeList[9]: 'কন্নড়',
      langCodeList[10]: 'উৰ্দু',
      langCodeList[11]: 'ডোগ্ৰী',
      langCodeList[12]: 'নেপালী',
      langCodeList[13]: 'সিংহলি',
      langCodeList[14]: 'সংস্কৃত',
      langCodeList[15]: 'অসমীয়া',
      langCodeList[16]: 'মৈথিলী',
      langCodeList[17]: 'ভোজপুৰী',
      langCodeList[18]: 'মালয়ালম',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'মণিপুৰী',
      langCodeList[22]: 'কাশ্মিৰী',
      langCodeList[23]: 'কোংকণী',
      langCodeList[24]: 'সিন্ধী',
      langCodeList[25]: 'চাঁওতালি'
    },
    // Maithili
    langCodeList[16]: {
      langCodeList[0]: 'अङरेजी',
      langCodeList[1]: 'हिन्दी',
      langCodeList[2]: 'मराठी',
      langCodeList[3]: 'बाङ्गला',
      langCodeList[4]: 'पञ्जाबी',
      langCodeList[5]: 'गुजराती',
      langCodeList[6]: 'ओड़िया',
      langCodeList[7]: 'तमिल',
      langCodeList[8]: 'तेलुगु',
      langCodeList[9]: 'कन्नड़',
      langCodeList[10]: 'उर्दू',
      langCodeList[11]: 'डोगरी',
      langCodeList[12]: 'नेपाली',
      langCodeList[13]: 'सिंहली',
      langCodeList[14]: 'संस्कृत',
      langCodeList[15]: 'असमिया',
      langCodeList[16]: 'मैथिली',
      langCodeList[17]: 'भोजपुरी',
      langCodeList[18]: 'मलयालम',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'मणिपुरी',
      langCodeList[22]: 'कश्मीरी',
      langCodeList[23]: 'कोङ्कणी',
      langCodeList[24]: 'सिन्धी',
      langCodeList[25]: 'संथाली'
    },
    // Bhojpuri
    langCodeList[17]: {
      langCodeList[0]: 'अंग्रेजी',
      langCodeList[1]: 'हिंदी',
      langCodeList[2]: 'मराठी',
      langCodeList[3]: 'बांग्ला',
      langCodeList[4]: 'पंजाबी',
      langCodeList[5]: 'गुजराती',
      langCodeList[6]: 'ओड़िया',
      langCodeList[7]: 'तमिल',
      langCodeList[8]: 'तेलुगु',
      langCodeList[9]: 'कन्नड़',
      langCodeList[10]: 'उर्दू',
      langCodeList[11]: 'डोगरी',
      langCodeList[12]: 'नेपाली',
      langCodeList[13]: 'सिंहली',
      langCodeList[14]: 'संस्कृत',
      langCodeList[15]: 'असमिया',
      langCodeList[16]: 'मैथिली',
      langCodeList[17]: 'भोजपुरी',
      langCodeList[18]: 'मलयालम',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'मणिपुरी',
      langCodeList[22]: 'कश्मीरी',
      langCodeList[23]: 'कोंकणी',
      langCodeList[24]: 'सिंधी',
      langCodeList[25]: 'संथाली'
    },
    // Malayalam
    langCodeList[18]: {
      langCodeList[0]: 'ഇംഗ്ലീഷ്',
      langCodeList[1]: 'ഹിന്ദി',
      langCodeList[2]: 'മറാത്തി',
      langCodeList[3]: 'ബംഗ്ല',
      langCodeList[4]: 'പഞ്ചാബി',
      langCodeList[5]: 'ഗുജറാത്തി',
      langCodeList[6]: 'ഒറിയ',
      langCodeList[7]: 'തമിഴ്',
      langCodeList[8]: 'തെലുങ്ക്',
      langCodeList[9]: 'കന്നഡ',
      langCodeList[10]: 'ഉർദു',
      langCodeList[11]: 'ഡോഗ്‌രി',
      langCodeList[12]: 'നേപ്പാളി',
      langCodeList[13]: 'സിംഹള',
      langCodeList[14]: 'സംസ്കൃതം',
      langCodeList[15]: 'ആസാമീസ്',
      langCodeList[16]: 'മൈഥിലി',
      langCodeList[17]: 'ഭോജ്പൂരി',
      langCodeList[18]: 'മലയാളം',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'മണിപ്പൂരി',
      langCodeList[22]: 'കാഷ്മീരി',
      langCodeList[23]: 'കൊങ്കണി',
      langCodeList[24]: 'സിന്ധി',
      langCodeList[25]: 'സന്താളി'
    },
    // Manipuri
    langCodeList[21]: {
      langCodeList[0]: 'ꯏꯪꯒ꯭ꯔꯥꯖꯤ',
      langCodeList[1]: 'ꯍꯤꯟꯗꯤ',
      langCodeList[2]: 'ꯃꯔꯥꯊꯤ',
      langCodeList[3]: 'ꯕꯪꯒ꯭ꯂꯥ',
      langCodeList[4]: 'ꯄꯟꯖꯥꯕꯤ',
      langCodeList[5]: 'ꯒꯨꯖꯔꯥꯇꯤ',
      langCodeList[6]: 'ꯑꯣꯔꯤꯌꯥ',
      langCodeList[7]: 'ꯇꯃꯤꯜ',
      langCodeList[8]: 'ꯇꯦꯂꯨꯒꯨ',
      langCodeList[9]: 'ꯀꯟꯅꯥꯗꯥ',
      langCodeList[10]: 'ꯎꯔꯗꯨ',
      langCodeList[11]: 'ꯗꯣꯒ꯭ꯔꯤ',
      langCodeList[12]: 'ꯅꯦꯄꯥꯂꯤ',
      langCodeList[13]: 'ꯁꯤꯟꯍꯥꯂꯥ',
      langCodeList[14]: 'ꯁꯟꯁꯀ꯭ꯔꯤꯠ',
      langCodeList[15]: 'ꯑꯁꯥꯃꯤꯁ',
      langCodeList[16]: 'ꯃꯩꯊꯤꯂꯤ',
      langCodeList[17]: 'ꯚꯣꯖꯄꯨꯔꯤ',
      langCodeList[18]: 'ꯃꯂꯌꯥꯂꯝ',
      langCodeList[19]: '',
      langCodeList[20]: '',
      langCodeList[21]: 'ꯃꯅꯤꯄꯨꯔꯤ',
      langCodeList[22]: 'ꯀꯁꯃꯤꯔꯤ',
      langCodeList[23]: 'ꯀꯣꯟꯀꯅꯤ',
      langCodeList[24]: 'ꯁꯤꯟꯙꯤ',
      langCodeList[25]: 'ꯁꯟꯊꯥꯂꯤ'
    },
  };
}
