import 'package:flutter/material.dart';

const Color primaryColor = Color(0XFFFF9933);
const Color flushOrangeColor = Color(0xFFFF8000);
const Color tangerineOrangeColor = Color(0xFFFB7D00);
const Color bisqueOrangeColor = Color(0xFFFFE5CC);
const Color frolyRed = Color(0xFFEA929D);
const Color brickRed = Color(0xFFD1293D);
const Color balticSea = Color(0xFF202330);
const Color dolphinGray = Color(0xFF6A6C75);
const Color goastWhite = Color(0xFFF2F2F3);
const Color manateeGray = Color(0xFF9C9DA3);
const Color sassyGreen = Color(0xFFE7F3E6);
const Color neonGreen = Color(0xFFB8DBB5);
const Color japaneseLaurel = Color(0xFF128807);
const Color americanSilver = Color(0xFFCDCED1);
const Color arsenicColor = Color(0xFF393B47);
const Color approxKarry = Color(0xFFFFE0C2);
const Color brightGrey = Color(0xFF51545E);
const Color mischkaGrey = Color(0xFFB5B6BA);
const Color lilyWhite = Color(0xFFE1F4EA);
const Color lilyGrey = Color(0xFFECF8F1);
const Color magicMint = Color(0xFFB0E3C9);
const Color honeydew = Color(0xFFF5FAF5);
